package json_test

import (
	"testing"

	"github.com/gpdf-dev/gpdf/_examples/testutil"
	"github.com/gpdf-dev/gpdf/template"
)

func TestJSON_13_HeaderFooter(t *testing.T) {
	pageBody := `{"body": [
		{"row": {"cols": [
			{"span": 12, "elements": [
				{"type": "text", "content": "Main Content Area", "style": {"size": 16, "bold": true}},
				{"type": "spacer", "height": "5mm"},
				{"type": "text", "content": "This page demonstrates header and footer repeated on every page. The header contains the company name and document title. The footer contains generation info and a confidentiality notice."}
			]}
		]}}
	]}`

	schema := []byte(`{
		"page": {"size": "A4", "margins": "20mm"},
		"header": [
			{"row": {"cols": [
				{"span": 6, "text": "ACME Corporation", "style": {"bold": true, "size": 10}},
				{"span": 6, "text": "Confidential Report", "style": {"align": "right", "size": 10, "color": "gray(0.5)"}}
			]}},
			{"row": {"cols": [
				{"span": 12, "elements": [
					{"type": "line", "line": {"color": "#1565C0", "thickness": "2pt"}},
					{"type": "spacer", "height": "5mm"}
				]}
			]}}
		],
		"footer": [
			{"row": {"cols": [
				{"span": 12, "elements": [
					{"type": "spacer", "height": "5mm"},
					{"type": "line", "line": {"color": "gray(0.7)"}},
					{"type": "spacer", "height": "2mm"}
				]}
			]}},
			{"row": {"cols": [
				{"span": 6, "text": "Generated by gpdf", "style": {"size": 8, "color": "gray(0.5)"}},
				{"span": 6, "text": "Confidential", "style": {"align": "right", "size": 8, "color": "gray(0.5)"}}
			]}}
		],
		"pages": [
			` + pageBody + `,
			` + pageBody + `,
			` + pageBody + `
		]
	}`)

	doc, err := template.FromJSON(schema, nil)
	if err != nil {
		t.Fatalf("FromJSON error: %v", err)
	}
	testutil.GeneratePDFSharedGolden(t, "13_header_footer.pdf", doc)
}
