package json_test

import (
	"fmt"
	"testing"

	"github.com/gpdf-dev/gpdf/_examples/testutil"
	"github.com/gpdf-dev/gpdf/template"
)

func TestJSON_26_PageNumber(t *testing.T) {
	titles := []string{"Introduction", "Background", "Analysis", "Conclusion"}
	contentText := "This is the content of the page. The footer displays the current page number, and the header shows the total number of pages in the document. Both are automatically updated after pagination, including on overflow pages."

	var pages string
	for i, title := range titles {
		if i > 0 {
			pages += ","
		}
		pages += fmt.Sprintf(`{"body": [
			{"row": {"cols": [
				{"span": 12, "elements": [
					{"type": "text", "content": "%s", "style": {"size": 18, "bold": true}},
					{"type": "spacer", "height": "5mm"},
					{"type": "text", "content": "%s"}
				]}
			]}}
		]}`, title, contentText)
	}

	schema := []byte(`{
		"page": {"size": "A4", "margins": "20mm"},
		"metadata": {"title": "Page Number Demo", "author": "gpdf"},
		"header": [
			{"row": {"cols": [
				{"span": 6, "text": "Page Number Demo", "style": {"bold": true, "size": 10}},
				{"span": 6, "elements": [
					{"type": "totalPages", "style": {"align": "right", "size": 9, "color": "gray(0.5)"}}
				]}
			]}},
			{"row": {"cols": [
				{"span": 12, "elements": [
					{"type": "line", "line": {"color": "#1565C0"}},
					{"type": "spacer", "height": "3mm"}
				]}
			]}}
		],
		"footer": [
			{"row": {"cols": [
				{"span": 12, "elements": [
					{"type": "spacer", "height": "3mm"},
					{"type": "line", "line": {"color": "gray(0.7)"}},
					{"type": "spacer", "height": "2mm"}
				]}
			]}},
			{"row": {"cols": [
				{"span": 6, "text": "Generated by gpdf", "style": {"size": 8, "color": "gray(0.5)"}},
				{"span": 6, "elements": [
					{"type": "pageNumber", "style": {"align": "right", "size": 8, "color": "gray(0.5)"}}
				]}
			]}}
		],
		"pages": [` + pages + `]
	}`)

	doc, err := template.FromJSON(schema, nil)
	if err != nil {
		t.Fatalf("FromJSON error: %v", err)
	}
	testutil.GeneratePDFSharedGolden(t, "26_page_number.pdf", doc)
}
