package examples_test

import (
	"testing"

	"github.com/gpdf-dev/gpdf/template"
)

func TestExample_30_JSON_13_HeaderFooter(t *testing.T) {
	schema := []byte(`{
		"page": {"size": "A4", "margins": "20mm"},
		"header": [
			{"row": {"cols": [
				{"span": 6, "text": "ACME Corporation", "style": {"bold": true, "size": 10}},
				{"span": 6, "text": "Confidential Report", "style": {"align": "right", "size": 10, "color": "#808080"}}
			]}},
			{"row": {"cols": [
				{"span": 12, "line": {"color": "#1565C0", "thickness": "2pt"}}
			]}},
			{"row": {"cols": [
				{"span": 12, "spacer": "5mm"}
			]}}
		],
		"footer": [
			{"row": {"cols": [
				{"span": 12, "spacer": "5mm"}
			]}},
			{"row": {"cols": [
				{"span": 12, "line": {"color": "#B3B3B3"}}
			]}},
			{"row": {"cols": [
				{"span": 12, "spacer": "2mm"}
			]}},
			{"row": {"cols": [
				{"span": 6, "text": "Generated by gpdf", "style": {"size": 8, "color": "#808080"}},
				{"span": 6, "text": "Confidential", "style": {"align": "right", "size": 8, "color": "#808080"}}
			]}}
		],
		"body": [
			{"row": {"cols": [
				{"span": 12, "text": "Main Content Area", "style": {"size": 16, "bold": true}}
			]}},
			{"row": {"cols": [
				{"span": 12, "spacer": "5mm"}
			]}},
			{"row": {"cols": [
				{"span": 12, "text": "This document demonstrates the use of headers and footers in JSON schema-based PDF generation. The header appears at the top of every page with the company name and a confidential marker. The footer includes a generation note and confidentiality reminder."}
			]}}
		]
	}`)

	doc, err := template.FromJSON(schema, nil)
	if err != nil {
		t.Fatalf("FromJSON error: %v", err)
	}
	generatePDF(t, "30_json_13_header_footer.pdf", doc)
}
