package examples_test

import (
	"testing"

	"github.com/gpdf-dev/gpdf/template"
)

func TestExample_31_Tmpl_13_HeaderFooter(t *testing.T) {
	schema := []byte(`{
		"page": {"size": "A4", "margins": "20mm"},
		"header": [
			{"row": {"cols": [
				{"span": 6, "text": "{{.Company}}", "style": {"bold": true, "size": 10}},
				{"span": 6, "text": "{{.DocTitle}}", "style": {"align": "right", "size": 10, "color": "#808080"}}
			]}},
			{"row": {"cols": [
				{"span": 12, "line": {"color": "#1565C0", "thickness": "2pt"}}
			]}},
			{"row": {"cols": [
				{"span": 12, "spacer": "5mm"}
			]}}
		],
		"footer": [
			{"row": {"cols": [
				{"span": 12, "spacer": "5mm"}
			]}},
			{"row": {"cols": [
				{"span": 12, "line": {"color": "#B3B3B3"}}
			]}},
			{"row": {"cols": [
				{"span": 12, "spacer": "2mm"}
			]}},
			{"row": {"cols": [
				{"span": 6, "text": "{{.FooterLeft}}", "style": {"size": 8, "color": "#808080"}},
				{"span": 6, "text": "{{.FooterRight}}", "style": {"align": "right", "size": 8, "color": "#808080"}}
			]}}
		],
		"body": [
			{"row": {"cols": [
				{"span": 12, "text": "{{.ContentTitle}}", "style": {"size": 16, "bold": true}}
			]}},
			{"row": {"cols": [
				{"span": 12, "spacer": "5mm"}
			]}},
			{"row": {"cols": [
				{"span": 12, "text": "{{.ContentText}}"}
			]}}
		]
	}`)

	data := map[string]any{
		"Company":      "ACME Corporation",
		"DocTitle":     "Confidential Report",
		"FooterLeft":   "Generated by gpdf",
		"FooterRight":  "Confidential",
		"ContentTitle": "Main Content Area",
		"ContentText":  "This document demonstrates header and footer support with Go template placeholders. The header contains the company name and document title. The footer includes a generation note and a confidentiality notice. All text values are provided through template data.",
	}

	doc, err := template.FromJSON(schema, data)
	if err != nil {
		t.Fatalf("FromJSON error: %v", err)
	}
	generatePDF(t, "31_tmpl_13_header_footer.pdf", doc)
}
