package examples_test

import (
	"testing"

	"github.com/gpdf-dev/gpdf/template"
)

func TestExample_31_Tmpl_26_PageNumber(t *testing.T) {
	schema := []byte(`{
		"page": {"size": "A4", "margins": "20mm"},
		"metadata": {"title": "{{.MetaTitle}}", "author": "{{.MetaAuthor}}"},
		"header": [
			{"row": {"cols": [
				{"span": 6, "text": "{{.HeaderTitle}}", "style": {"bold": true, "size": 10}},
				{"span": 6, "elements": [
					{"type": "totalPages", "style": {"align": "right", "size": 9, "color": "#808080"}}
				]}
			]}},
			{"row": {"cols": [
				{"span": 12, "elements": [
					{"type": "line", "line": {"color": "#1565C0"}},
					{"type": "spacer", "height": "3mm"}
				]}
			]}}
		],
		"footer": [
			{"row": {"cols": [
				{"span": 12, "elements": [
					{"type": "spacer", "height": "3mm"},
					{"type": "line", "line": {"color": "#B3B3B3"}},
					{"type": "spacer", "height": "2mm"}
				]}
			]}},
			{"row": {"cols": [
				{"span": 6, "text": "{{.FooterText}}", "style": {"size": 8, "color": "#808080"}},
				{"span": 6, "elements": [
					{"type": "pageNumber", "style": {"align": "right", "size": 8, "color": "#808080"}}
				]}
			]}}
		],
		"body": [
			{"row": {"cols": [
				{"span": 12, "text": "{{.Section1}}", "style": {"size": 18, "bold": true}}
			]}},
			{"row": {"cols": [
				{"span": 12, "spacer": "5mm"}
			]}},
			{"row": {"cols": [
				{"span": 12, "text": "This is the content of the page. The footer displays the current page number, and the header shows the total number of pages in the document. Both are automatically updated after pagination, including on overflow pages."}
			]}},
			{"row": {"cols": [
				{"span": 12, "spacer": "10mm"}
			]}},
			{"row": {"cols": [
				{"span": 12, "text": "{{.Section2}}", "style": {"size": 18, "bold": true}}
			]}},
			{"row": {"cols": [
				{"span": 12, "spacer": "5mm"}
			]}},
			{"row": {"cols": [
				{"span": 12, "text": "This is the content of the page. The footer displays the current page number, and the header shows the total number of pages in the document. Both are automatically updated after pagination, including on overflow pages."}
			]}},
			{"row": {"cols": [
				{"span": 12, "spacer": "10mm"}
			]}},
			{"row": {"cols": [
				{"span": 12, "text": "{{.Section3}}", "style": {"size": 18, "bold": true}}
			]}},
			{"row": {"cols": [
				{"span": 12, "spacer": "5mm"}
			]}},
			{"row": {"cols": [
				{"span": 12, "text": "This is the content of the page. The footer displays the current page number, and the header shows the total number of pages in the document. Both are automatically updated after pagination, including on overflow pages."}
			]}},
			{"row": {"cols": [
				{"span": 12, "spacer": "10mm"}
			]}},
			{"row": {"cols": [
				{"span": 12, "text": "{{.Section4}}", "style": {"size": 18, "bold": true}}
			]}},
			{"row": {"cols": [
				{"span": 12, "spacer": "5mm"}
			]}},
			{"row": {"cols": [
				{"span": 12, "text": "This is the content of the page. The footer displays the current page number, and the header shows the total number of pages in the document. Both are automatically updated after pagination, including on overflow pages."}
			]}}
		]
	}`)

	data := map[string]any{
		"MetaTitle":   "Page Number Demo",
		"MetaAuthor":  "gpdf",
		"HeaderTitle": "Page Number Demo",
		"FooterText":  "Generated by gpdf",
		"Section1":    "Introduction",
		"Section2":    "Background",
		"Section3":    "Analysis",
		"Section4":    "Conclusion",
	}

	doc, err := template.FromJSON(schema, data)
	if err != nil {
		t.Fatalf("FromJSON error: %v", err)
	}
	generatePDF(t, "31_tmpl_26_page_number.pdf", doc)
}
