package overlay_test

import (
	"testing"

	gpdf "github.com/gpdf-dev/gpdf"
	"github.com/gpdf-dev/gpdf/_examples/testutil"
	"github.com/gpdf-dev/gpdf/document"
	"github.com/gpdf-dev/gpdf/pdf"
	"github.com/gpdf-dev/gpdf/template"
)

func TestExample_Overlay_05_Facade(t *testing.T) {
	// Generate a source PDF using the standard API.
	source := generateSourcePDF(t, 2)

	// Open via the gpdf.Open facade.
	doc, err := gpdf.Open(source)
	if err != nil {
		t.Fatalf("gpdf.Open: %v", err)
	}

	// Add a watermark on page 1.
	err = doc.Overlay(0, func(p *template.PageBuilder) {
		p.Absolute(document.Mm(50), document.Mm(140), func(c *template.ColBuilder) {
			c.Text("SAMPLE",
				template.FontSize(60),
				template.TextColor(pdf.Color{R: 0.85, G: 0.85, B: 0.85, A: 1, Space: pdf.ColorSpaceRGB}),
			)
		})
	})
	if err != nil {
		t.Fatalf("Overlay: %v", err)
	}

	// Add footer on page 2.
	err = doc.Overlay(1, func(p *template.PageBuilder) {
		p.Absolute(document.Mm(20), document.Mm(280), func(c *template.ColBuilder) {
			c.Text("Generated by gpdf",
				template.FontSize(8),
				template.TextColor(pdf.Gray(0.5)),
			)
		})
	})
	if err != nil {
		t.Fatalf("Overlay page 2: %v", err)
	}

	result, err := doc.Save()
	if err != nil {
		t.Fatalf("Save: %v", err)
	}

	testutil.AssertValidPDF(t, result)
	testutil.WritePDF(t, "05_facade.pdf", result)
}
