package gotemplate_test

import (
	"fmt"
	"testing"

	"github.com/gpdf-dev/gpdf/_examples/testutil"
	"github.com/gpdf-dev/gpdf/template"
)

func TestTmpl_26_PageNumber(t *testing.T) {
	titles := []string{"Introduction", "Background", "Analysis", "Conclusion"}
	contentText := "This is the content of the page. The footer displays the current page number, and the header shows the total number of pages in the document. Both are automatically updated after pagination, including on overflow pages."

	var pages string
	for i, title := range titles {
		if i > 0 {
			pages += ","
		}
		pages += fmt.Sprintf(`{"body": [
			{"row": {"cols": [
				{"span": 12, "elements": [
					{"type": "text", "content": "{{.Title%d}}", "style": {"size": 18, "bold": true}},
					{"type": "spacer", "height": "5mm"},
					{"type": "text", "content": "{{.ContentText}}"}
				]}
			]}}
		]}`, i)
		_ = title // used in data map below
	}

	schema := []byte(`{
		"page": {"size": "A4", "margins": "20mm"},
		"metadata": {"title": "{{.MetaTitle}}", "author": "{{.MetaAuthor}}"},
		"header": [
			{"row": {"cols": [
				{"span": 6, "text": "{{.HeaderTitle}}", "style": {"bold": true, "size": 10}},
				{"span": 6, "elements": [
					{"type": "totalPages", "style": {"align": "right", "size": 9, "color": "gray(0.5)"}}
				]}
			]}},
			{"row": {"cols": [
				{"span": 12, "elements": [
					{"type": "line", "line": {"color": "#1565C0"}},
					{"type": "spacer", "height": "3mm"}
				]}
			]}}
		],
		"footer": [
			{"row": {"cols": [
				{"span": 12, "elements": [
					{"type": "spacer", "height": "3mm"},
					{"type": "line", "line": {"color": "gray(0.7)"}},
					{"type": "spacer", "height": "2mm"}
				]}
			]}},
			{"row": {"cols": [
				{"span": 6, "text": "{{.FooterText}}", "style": {"size": 8, "color": "gray(0.5)"}},
				{"span": 6, "elements": [
					{"type": "pageNumber", "style": {"align": "right", "size": 8, "color": "gray(0.5)"}}
				]}
			]}}
		],
		"pages": [` + pages + `]
	}`)

	data := map[string]any{
		"MetaTitle":   "Page Number Demo",
		"MetaAuthor":  "gpdf",
		"HeaderTitle": "Page Number Demo",
		"FooterText":  "Generated by gpdf",
		"Title0":      titles[0],
		"Title1":      titles[1],
		"Title2":      titles[2],
		"Title3":      titles[3],
		"ContentText": contentText,
	}

	doc, err := template.FromJSON(schema, data)
	if err != nil {
		t.Fatalf("FromJSON error: %v", err)
	}
	testutil.GeneratePDFSharedGolden(t, "26_page_number.pdf", doc)
}
