package builder_test

import (
	"testing"

	"github.com/gpdf-dev/gpdf/_examples/testutil"
	"github.com/gpdf-dev/gpdf/document"
	"github.com/gpdf-dev/gpdf/pdf"
	"github.com/gpdf-dev/gpdf/template"
)

func TestExample_13_HeaderFooter(t *testing.T) {
	doc := template.New(
		template.WithPageSize(document.A4),
		template.WithMargins(document.UniformEdges(document.Mm(20))),
	)

	// Header: company name on left, document title on right
	doc.Header(func(p *template.PageBuilder) {
		p.AutoRow(func(r *template.RowBuilder) {
			r.Col(6, func(c *template.ColBuilder) {
				c.Text("ACME Corporation", template.Bold(), template.FontSize(10))
			})
			r.Col(6, func(c *template.ColBuilder) {
				c.Text("Confidential Report", template.AlignRight(), template.FontSize(10),
					template.TextColor(pdf.Gray(0.5)))
			})
		})
		p.AutoRow(func(r *template.RowBuilder) {
			r.Col(12, func(c *template.ColBuilder) {
				c.Line(template.LineColor(pdf.RGBHex(0x1565C0)), template.LineThickness(document.Pt(2)))
				c.Spacer(document.Mm(5))
			})
		})
	})

	// Footer: centered text with line separator
	doc.Footer(func(p *template.PageBuilder) {
		p.AutoRow(func(r *template.RowBuilder) {
			r.Col(12, func(c *template.ColBuilder) {
				c.Spacer(document.Mm(5))
				c.Line(template.LineColor(pdf.Gray(0.7)))
				c.Spacer(document.Mm(2))
			})
		})
		p.AutoRow(func(r *template.RowBuilder) {
			r.Col(6, func(c *template.ColBuilder) {
				c.Text("Generated by gpdf", template.FontSize(8), template.TextColor(pdf.Gray(0.5)))
			})
			r.Col(6, func(c *template.ColBuilder) {
				c.Text("Confidential", template.FontSize(8),
					template.AlignRight(), template.TextColor(pdf.Gray(0.5)))
			})
		})
	})

	// Three pages of content
	for range 3 {
		page := doc.AddPage()
		page.AutoRow(func(r *template.RowBuilder) {
			r.Col(12, func(c *template.ColBuilder) {
				c.Text("Main Content Area", template.FontSize(16), template.Bold())
				c.Spacer(document.Mm(5))
				c.Text("This page demonstrates header and footer repeated on every page. " +
					"The header contains the company name and document title. " +
					"The footer contains generation info and a confidentiality notice.")
			})
		})
	}

	testutil.GeneratePDFSharedGolden(t, "13_header_footer.pdf", doc)
}
