package builder_test

import (
	"testing"

	"github.com/gpdf-dev/gpdf/_examples/testutil"
	"github.com/gpdf-dev/gpdf/document"
	"github.com/gpdf-dev/gpdf/pdf"
	"github.com/gpdf-dev/gpdf/template"
)

func TestExample_26_PageNumber(t *testing.T) {
	doc := template.New(
		template.WithPageSize(document.A4),
		template.WithMargins(document.UniformEdges(document.Mm(20))),
		template.WithMetadata(document.DocumentMetadata{
			Title:  "Page Number Demo",
			Author: "gpdf",
		}),
	)

	// Header with total pages
	doc.Header(func(p *template.PageBuilder) {
		p.AutoRow(func(r *template.RowBuilder) {
			r.Col(6, func(c *template.ColBuilder) {
				c.Text("Page Number Demo", template.Bold(), template.FontSize(10))
			})
			r.Col(6, func(c *template.ColBuilder) {
				c.TotalPages(template.AlignRight(), template.FontSize(9),
					template.TextColor(pdf.Gray(0.5)))
			})
		})
		p.AutoRow(func(r *template.RowBuilder) {
			r.Col(12, func(c *template.ColBuilder) {
				c.Line(template.LineColor(pdf.RGBHex(0x1565C0)))
				c.Spacer(document.Mm(3))
			})
		})
	})

	// Footer with page number
	doc.Footer(func(p *template.PageBuilder) {
		p.AutoRow(func(r *template.RowBuilder) {
			r.Col(12, func(c *template.ColBuilder) {
				c.Spacer(document.Mm(3))
				c.Line(template.LineColor(pdf.Gray(0.7)))
				c.Spacer(document.Mm(2))
			})
		})
		p.AutoRow(func(r *template.RowBuilder) {
			r.Col(6, func(c *template.ColBuilder) {
				c.Text("Generated by gpdf", template.FontSize(8),
					template.TextColor(pdf.Gray(0.5)))
			})
			r.Col(6, func(c *template.ColBuilder) {
				c.PageNumber(template.AlignRight(), template.FontSize(8),
					template.TextColor(pdf.Gray(0.5)))
			})
		})
	})

	// Create 4 pages of content
	for i := range 4 {
		page := doc.AddPage()
		page.AutoRow(func(r *template.RowBuilder) {
			r.Col(12, func(c *template.ColBuilder) {
				titles := []string{
					"Introduction",
					"Background",
					"Analysis",
					"Conclusion",
				}
				c.Text(titles[i], template.FontSize(18), template.Bold())
				c.Spacer(document.Mm(5))
				c.Text("This is the content of the page. The footer displays the " +
					"current page number, and the header shows the total number " +
					"of pages in the document. Both are automatically updated " +
					"after pagination, including on overflow pages.")
			})
		})
	}

	testutil.GeneratePDFSharedGolden(t, "26_page_number.pdf", doc)
}
